# Site settings
title: CS373 Fall 2017: Nick Ginther
baseurl: ""
url: "http://nginth.github.io"

# Build settings
kramdown:
  input: GFM
  parse_block_html: true
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname:
